Repository Dev-FE-1/woowahan-siblings, pull requests merged in 2024-08, with the labels that each got.

#52 [fix] React Router Link 및 Span 컴포넌트에서 사용자 정의 속성 제거
  src/layout/Menu/MenuItem.tsx
Labels: 🐞 BugFix

#53 [feature] 캘린더 컴포넌트 퍼블리싱 완료
  src/components/Calendar/Calendar.tsx
  src/components/Calendar/CalendarBadge.tsx
  src/components/Calendar/CalendarDates.tsx
  src/components/Calendar/CalendarWeek.tsx
  src/components/Calendar/CalenderContents.tsx
  src/components/Calendar/ControlDate.tsx
  src/components/Calendar/mockdata.ts
  src/components/IconButton.tsx
  src/constants/badgeColors.ts
  src/interfaces/calendar.d.ts
  src/interfaces/iconButton.d.ts
  src/pages/Home.tsx
  src/utils/getMonthList.tsx
Labels: ✨ Feature, 🎨 Design

#54 [Feature] 급여 탭 메뉴, 이전달/다음달 이동 버튼
  package-lock.json
  package.json
  src/components/Divider.tsx
  src/components/Wage/ControlMonth.tsx
  src/components/Wage/SalaryCard.tsx
  src/components/Wage/WageMockData.tsx
  src/components/Wage/WageTab.tsx
  src/layout/Header.tsx
  src/pages/Wage/Wage.tsx
  src/pages/Wage/WageCheck/WageCheck.tsx
Labels: ✨ Feature, 🎨 Design

#56 [feat] Input, Button 컴포넌트 생성
  src/components/Button.tsx
  src/components/Input.tsx
  src/constants/colors.ts
  src/interfaces/button.d.ts
  src/interfaces/input.d.ts
Labels: ✨ Feature

#57 [feature] 모달 기본 레이아웃 설정 리덕스 툴킷 사용 #19
  package-lock.json
  package.json
  src/components/ScheduleModal.tsx
  src/main.tsx
  src/pages/Schedule/Schedule.tsx
  src/stores/modalSlice.ts
  src/stores/store.ts
Labels: ✨ Feature

#59 [fix] 스크롤 이슈 수정 및 레이아웃 개선
  src/layout/Content.tsx
  src/layout/Layout.tsx
  src/styles/GlobalStyles.tsx
Labels: 🐞 BugFix

#61 [design] 캘린더, 아이콘 버튼 UI 수정
  src/components/Calendar/CalendarBadge.tsx
  src/components/Calendar/CalendarDates.tsx
  src/components/Calendar/CalendarWeek.tsx
  src/components/Calendar/CalenderContents.tsx
  src/components/Calendar/ControlDate.tsx
  src/components/IconButton.tsx
Labels: 🎨 Design

#60 [feature] 모달 기능 조금 구현 퍼플리싱 했음 #20
  src/components/Calendar/mockdata.ts
  src/components/ScheduleModal.tsx
Labels: ✨ Feature

#64 [chore] 파비콘, 사이트 타이틀, 언어 ko 변경
  index.html
  public/favicon.ico
  public/vite.svg
Labels: ⚙ Settings

#65 [Feat] 더보기버튼, 급여내역 작업
  package-lock.json
  src/components/Wage/WageMockData.tsx
  src/components/Wage/WorkHistory.tsx
  src/components/Wage/workHistoryData.tsx
  src/pages/Wage/WageCheck/WageCheck.tsx
  src/pages/Wage/WageCheck/WageCheckDetail.tsx
Labels: ✨ Feature, 🎨 Design

#67 [feature] 홈페이지 UI 퍼블리싱 작업
  src/components/Home/SummaryInfoCard.tsx
  src/pages/Home.tsx
Labels: ✨ Feature, 🎨 Design

#69 [Design]급여 상세내역 UI
  src/constants/font.ts
  src/pages/Wage/WageCheck/WageCheckDetail.tsx
Labels: 🎨 Design

#70 [feature] 로그인 기능 구현
  package-lock.json
  package.json
  src/App.tsx
  src/api/auth/checkAuth.ts
  src/api/auth/login.ts
  src/constants/colors.ts
  src/interfaces/privateRoute.d.ts
  src/layout/Layout.tsx
  src/pages/Login.tsx
Labels: ✨ Feature, 🔥 Firebase

#72 [feature] 모달 컴포넌트 정리 , 일정 수정 삭제 기능 구현
  package-lock.json
  package.json
  src/components/Calendar/mockdata.ts
  src/components/Modal/ModalContent.tsx
  src/components/Modal/ModalHeader.tsx
  src/components/Modal/ModalOverlay.tsx
  src/components/ScheduleModal.tsx
  src/components/SheduleModal/ScheduleModal.tsx
  src/components/SheduleModal/ScheduleModalFooter.tsx
  src/components/SheduleModal/ScheduleModalForm.tsx
  src/interfaces/scheduleModal.d.ts
  src/layout/Layout.tsx
  src/pages/Schedule/Schedule.tsx
Labels: ✨ Feature

#74 [bug] package.json 중복 요소 삭제
  package.json
Labels: 🐞 BugFix

#76 [Design] layout컴포넌트 css, 급여확인 css 수정
  src/components/Wage/ControlMonth.tsx
  src/components/Wage/WageTab.tsx
  src/components/Wage/WorkHistory.tsx
  src/constants/font.ts
  src/layout/Header.tsx
  src/layout/Layout.tsx
  src/layout/Menu/Menu.tsx
  src/layout/Menu/MenuItem.tsx
  src/pages/Wage/Wage.tsx
  src/pages/Wage/WageCheck/WageCheck.tsx
  src/pages/Wage/WageCheck/WageCheckDetail.tsx
  src/styles/GlobalStyles.tsx
Labels: 🎨 Design

#78 [Bug] 강사님 피드백 적용
  src/App.tsx
  src/components/Divider.tsx
  src/components/Home/SummaryInfoCard.tsx
  src/components/SheduleModal/ScheduleModal.tsx
  src/components/SheduleModal/ScheduleModalFooter.tsx
  src/components/SheduleModal/ScheduleModalForm.tsx
  src/components/Wage/ControlMonth.tsx
  src/components/Wage/SalaryCard.tsx
  src/components/Wage/WageTab.tsx
  src/components/Wage/WorkHistory.tsx
  src/components/common/Button/Button.tsx
  src/components/common/Button/IconButton.tsx
  src/components/common/Calendar/Calendar.tsx
  src/components/common/Calendar/CalendarBadge.tsx
  src/components/common/Calendar/CalendarDates.tsx
  src/components/common/Calendar/CalendarWeek.tsx
  src/components/common/Calendar/CalenderContents.tsx
  src/components/common/Calendar/ControlDate.tsx
  src/components/common/Input.tsx
  src/components/common/Modal/ModalContent.tsx
  src/components/common/Modal/ModalHeader.tsx
  src/components/common/Modal/ModalOverlay.tsx
  src/data/mockdata.ts
  src/data/workHistoryData.ts
  src/interfaces/button.d.ts
  src/interfaces/calendar.d.ts
  src/interfaces/iconButton.d.ts
  src/interfaces/input.d.ts
  src/interfaces/menu.d.ts
  src/interfaces/privateRoute.d.ts
  src/interfaces/scheduleModal.d.ts
  src/layout/Content.tsx
  src/layout/Header.tsx
  src/layout/Menu/Menu.tsx
  src/layout/Menu/MenuItem.tsx
  src/pages/Home.tsx
  src/pages/Login.tsx
  src/pages/Profile.tsx
  src/pages/Schedule/Schedule.tsx
  src/pages/Schedule/ScheduleDetail.tsx
  src/pages/Wage/Correction/Correction.tsx
  src/pages/Wage/Correction/CorrectionDetail.tsx
  src/pages/Wage/Wage.tsx
  src/pages/Wage/WageCheck/WageCheck.tsx
  src/pages/Wage/WageCheck/WageCheckDetail.tsx
  src/stores/store.ts
Labels: 🐞 BugFix

#79 [Design] 프로필페이지 디자인
  .eslintrc.cjs
  src/components/Profile/ProfileMenu.tsx
  src/components/Profile/UserProfile.tsx
  src/pages/Profile.tsx
Labels: 🎨 Design

#81 [Feat]프로필페이지 메뉴들 라우팅
  src/App.tsx
  src/components/Profile/ProfileMenu.tsx
  src/pages/UnderConstruction.tsx
Labels: ✨ Feature, 🎨 Design

#84 [feature] Firebase API 공통 로직 구현
  package-lock.json
  src/api/auth/checkAuth.ts
  src/api/common/getDocsByUserId.ts
  src/api/common/getUserId.ts
Labels: ✨ Feature, 📬 API

#89 [feature] 급여, 프로필 페이지 API 구현
  src/api/common/getDocsByUserId.ts
  src/api/schedule/getOfficialSchedule.ts
  src/api/user/getUserInfo.ts
  src/api/work/createCorrection.ts
  src/api/work/getCorrection.ts
  src/api/work/getOfficialWage.ts
  src/api/work/getPersonalWage.ts
Labels: ✨ Feature, 📬 API

#101 [bug] Firestore 컬렉션 데이터, API 일부 수정
  src/api/schedule/getOfficialSchedule.ts
  src/api/work/getOfficialWage.ts
  src/api/work/getPersonalWage.ts
Labels: 🐞 BugFix, 📬 API, 🔥 Firebase

#104 [feature] 일정표 페이지 API 구현
  src/api/schedule/createPersonalSchedule.ts
  src/api/schedule/deletePersonalSchedule.ts
  src/api/schedule/getOfficialSchedule.ts
  src/api/schedule/getPersonalSchedule.ts
  src/api/schedule/updatePersonalSchedule.ts
  src/api/user/getUserInfo.ts
  src/api/work/createCorrection.ts
  src/api/work/getCorrection.ts
  src/api/work/getOfficialWage.ts
  src/api/work/getPersonalWage.ts
Labels: ✨ Feature, 📬 API, 🔥 Firebase

#111 [ remove] 파일중복으로 인한 getMonthList.ts 파일 삭제
  src/utils/getMonthList.ts
Labels: ✨ Feature

#113 [feature] 회원 정보 Redux 전역 상태 관리
  src/api/user/getUserInfo.ts
  src/pages/Profile.tsx
  src/stores/store.ts
  src/stores/userInfoSlice.ts
Labels: ✨ Feature

#114 [feat] 정정 신청 내역 페이지 구현(필터링, 더보기 기능)
  src/components/Wage/ApprovedStatusBadge.tsx
  src/components/Wage/CorrectionTable.tsx
  src/components/common/Dropdown.tsx
  src/components/common/Title.tsx
  src/data/correctionMockData.json
  src/pages/Wage/Correction/Correction.tsx
  src/utils/labelUtils.ts
Labels: ✨ Feature

#119 [feature] 일정 수정 삭제 추가 기능 완료
  src/components/SheduleModal/ScheduleModal.tsx
  src/components/SheduleModal/ScheduleModalForm.tsx
  src/components/common/Dropdown.tsx
  src/data/mockdata.ts
  src/pages/Schedule/ScheduleDetail.tsx
  src/utils/dateUtils.tsx
Labels: ✨ Feature

#123 [feature] 로그인 관련 기능 추가 구현
  src/api/auth/logout.ts
  src/components/Profile/ProfileMenu.tsx
  src/components/common/Button/UnderlineTextButton.tsx
  src/components/common/Input.tsx
  src/hooks/useLogin.ts
  src/pages/Login.tsx
  src/pages/Profile.tsx
Labels: ✨ Feature

#122 [design] 캘린더 디자인 변경하기  
  src/components/common/Calendar/CalendarDates.tsx
  src/components/common/Calendar/CalendarWeek.tsx
  src/components/common/Calendar/CalenderContents.tsx
  src/constants/colors.ts
  src/utils/dateUtils.tsx
Labels: 🎨 Design

#127 [feature] 모달 리덕스 연결 완료 했습니다 !!
  src/components/SheduleModal/ScheduleModal.tsx
  src/pages/Schedule/ScheduleDetail.tsx
  src/stores/scheduleSlice.ts
  src/stores/store.ts
Labels: ✨ Feature

#128 [feature] 라우팅 방식 개선
  src/App.tsx
Labels: ✨ Feature

#133 [bug] 로딩 기능 구현 PR 과정에서 발생한 conflict 미반영 사항 수정
  src/pages/Profile.tsx
  src/pages/Schedule/ScheduleDetail.tsx
Labels: 🐞 BugFix

#136 [feature] 라우팅 시 스크롤 상태 초기화 처리
  src/App.tsx
  src/components/ScrollToTop.tsx
Labels: ✨ Feature

#138 [bug] 개인근무일정페이지에서 일정 추가가 안되는 문제 해결
  src/components/common/Calendar/CalendarBadge.tsx
  src/components/common/Calendar/CalendarDates.tsx
  src/utils/dateUtils.tsx
Labels: 🐞 BugFix

#140 [feature] 리드미 파일 작성
  README.md
Labels: 📃 Docs

#144 [fix] 파일 확장자 통일 및 미사용 목데이터 삭제
  src/data/correctionMockData.json
  src/data/mockdata.ts
  src/utils/dateUtils.ts
  src/utils/getMonthList.ts
Labels: ⚙ Settings

#145 [bug] 드디어 캘린더에 발생했던 타입 불일치 버그를 고쳤습니다
  src/components/common/Dropdown.tsx
  src/utils/dateUtils.ts
Labels: 🐞 BugFix

#150 [bug] 이제 기존에 일정이 없어도 일정 추가가 제대로 진행됩니다
  src/components/SheduleModal/ScheduleModal.tsx
  src/pages/Schedule/ScheduleDetail.tsx
Labels: 🐞 BugFix

#153 [design] 로그인, 홈, 일정 페이지 css 디자인 최종수정
  src/App.tsx
  src/assets/character_cheese.svg
  src/assets/character_clock.svg
  src/assets/loading_duck.gif
  src/assets/logo.svg
  src/assets/logo_404.svg
  src/components/Home/SummaryInfoCard.tsx
  src/components/Loading/Loading.tsx
  src/components/Loading/LoadingDuck.tsx
  src/components/SheduleModal/ScheduleModalFooter.tsx
  src/components/SheduleModal/ScheduleModalForm.tsx
  src/components/common/Button/Button.tsx
  src/components/common/Calendar/Calendar.tsx
  src/components/common/Calendar/CalendarBadge.tsx
  src/components/common/Calendar/ControlDate.tsx
  src/components/common/Dropdown.tsx
  src/components/common/Input.tsx
  src/components/common/Modal/ModalContent.tsx
  src/components/common/Modal/ModalHeader.tsx
  src/components/common/Select.tsx
  src/constants/font.ts
  src/layout/Header.tsx
  src/layout/Menu/MenuItem.tsx
  src/pages/Home.tsx
  src/pages/Login.tsx
  src/pages/NotFoundPage.tsx
  src/pages/Profile.tsx
  src/pages/Schedule/Schedule.tsx
  src/pages/Schedule/ScheduleDetail.tsx
  src/pages/Wage/WageCheck/WageCheck.tsx
Labels: 🎨 Design

#154 [fix] 스케줄 관련 API 날짜 반환 방식 이슈 해결
  src/api/schedule/getOfficialSchedule.ts
  src/api/schedule/getPersonalSchedule.ts
  src/api/work/getOfficialWage.ts
Labels: 🐞 BugFix

#156 [bug] 오리파일 경로찾기 및 package-lock.json 업데이트
  package-lock.json
  src/components/Loading/Loading.tsx
Labels: 🐞 BugFix

#158 [design] 급여 내역, 정정 신청 페이지 css 최종 수정
  src/components/Wage/ControlMonth.tsx
  src/components/Wage/CorrectionTable.tsx
  src/components/Wage/SalaryCard.tsx
  src/components/Wage/WageTab.tsx
  src/components/Wage/WorkHistory.tsx
  src/components/common/Button/IconButton.tsx
  src/components/common/Dropdown.tsx
  src/constants/options.ts
  src/layout/Layout.tsx
  src/pages/Wage/Correction/Correction.tsx
  src/pages/Wage/WageCheck/WageCheck.tsx
  src/pages/Wage/WageCheck/WageCheckDetail.tsx
Labels: 🎨 Design

#162 [feature] 리드미 파일 수정
  README.md
Labels: 📃 Docs

#165 [refactor] API, 컴포넌트 관련 코드 리뷰 피드백 반영
  src/App.tsx
  src/api/common/getDocsByUserId.ts
  src/api/schedule/createPersonalSchedule.ts
  src/api/schedule/deletePersonalSchedule.ts
  src/api/schedule/getOfficialSchedule.ts
  src/api/schedule/getPersonalSchedule.ts
  src/api/schedule/updatePersonalSchedule.ts
  src/api/user/getUserInfo.ts
  src/api/work/createCorrection.ts
  src/api/work/getCorrection.ts
  src/api/work/getOfficialWage.ts
  src/api/work/getPersonalWage.ts
  src/components/ScrollToTop.tsx
  src/layout/Layout.tsx
  src/utils/scrollUtils.ts
  src/utils/userDataUtils.ts
Labels: 🔨 Refactor

#168 [refactor] 캘린더 관련 코드 리뷰 피드백 반영
  src/components/Home/SummaryInfoCard.tsx
  src/components/common/Calendar/CalendarDates.tsx
  src/components/common/Calendar/CalendarWeek.tsx
  src/components/common/Calendar/CalenderContents.tsx
  src/pages/Schedule/ScheduleDetail.tsx
  src/pages/Wage/WageCheck/WageCheckDetail.tsx
  src/utils/dateUtils.ts
  src/utils/getMonthList.ts
Labels: 🐞 BugFix

#172 [feature] 모달 피드백 전부 적용했습니다
  src/components/SheduleModal/ScheduleModal.tsx
  src/components/SheduleModal/ScheduleModalFooter.tsx
  src/utils/dateUtils.ts
Labels: ✨ Feature

#174 [refactor] 캘린더 2차 수정 작업
  src/components/Home/SummaryInfoCard.tsx
  src/components/common/Calendar/CalendarDates.tsx
  src/components/common/Calendar/CalenderContents.tsx
  src/pages/Home.tsx
Labels: 🔨 Refactor

#175 [refactor] 멘토님 코드리뷰 수정, 정정신청 상세페이지 추가, 메뉴 너비수정, 리드미 업데이트
  README.md
  src/api/schedule/createPersonalSchedule.ts
  src/api/schedule/deletePersonalSchedule.ts
  src/api/schedule/updatePersonalSchedule.ts
  src/api/work/createCorrection.ts
  src/api/work/getCorrection.ts
  src/components/ScheduleModal/ScheduleModal.tsx
  src/components/ScheduleModal/ScheduleModalFooter.tsx
  src/components/ScheduleModal/ScheduleModalForm.tsx
  src/components/Wage/ControlMonth.tsx
  src/components/Wage/CorrectionTable.tsx
  src/components/Wage/WorkHistory.tsx
  src/components/common/Calendar/CalenderContents.tsx
  src/components/common/Calendar/ControlDate.tsx
  src/components/common/Select.tsx
  src/hooks/useCorrections.ts
  src/layout/Menu/Menu.tsx
  src/layout/Menu/MenuItem.tsx
  src/pages/Schedule/ScheduleDetail.tsx
  src/pages/Wage/Correction/CorrectionDetail.tsx
  src/pages/Wage/Correction/CorrectionRequest.tsx
  src/pages/Wage/WageCheck/WageCheckDetail.tsx
  src/stores/correctionSlice.ts
  src/stores/store.ts
  src/types/commonTypes.ts
  src/types/correctionInterfaces.ts
  src/utils/dateUtils.ts
  src/utils/labelUtils.ts
Labels: 🔨 Refactor

#176 [deploy] firebase hosting 배포 추가
  .firebaserc
  .gitignore
  firebase.json
  package-lock.json
  package.json
Labels: 🌏 Deploy, 🔥 Firebase
