Repository Dev-FE-1/woowahan-siblings, pull requests merged in 2024-07, with the labels that each got.

#2 [docs] 이슈 템플릿 제목 수정
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/feature.yml
  .github/ISSUE_TEMPLATE/help.yml
Labels: documentation

#4 [docs] eslint 문서 수정
  .eslintrc.cjs
Labels: documentation

#5 [feat] develop -> main 머지하기
  .eslintrc.cjs
Labels: enhancement

#7 [docs] prettier 문서 수정
  .prettierrc
Labels: documentation

#10 [settings] eslint, emotion, husky, prettier 다 테스트, 수정 완료
  .eslintrc.cjs
  .husky/pre-commit
  package-lock.json
  package.json
  src/App.tsx
  src/main.tsx
  tsconfig.app.json
  vite.config.ts
Labels: enhancement

#22 [feature] 페이지 라우팅 세팅 완료
  .eslintrc.cjs
  package-lock.json
  package.json
  src/App.tsx
  src/main.tsx
  src/pages/Home.tsx
  src/pages/Profile.tsx
  src/pages/Schedule/Schedule.tsx
  src/pages/Schedule/ScheduleDetail.tsx
  src/pages/Wage/Correction/Correction.tsx
  src/pages/Wage/Correction/CorrectionDetail.tsx
  src/pages/Wage/Correction/CorrectionRequest.tsx
  src/pages/Wage/Wage.tsx
  src/pages/Wage/WageCheck/WageCheck.tsx
  src/pages/Wage/WageCheck/WageCheckDetail.tsx
Labels: ✨ Feature

#25 [feature] path alias 설정 완료
  package-lock.json
  package.json
  src/App.tsx
  src/pages/Wage/Correction/Correction.tsx
  src/pages/Wage/Correction/CorrectionDetail.tsx
  tsconfig.app.json
  tsconfig.node.json
  vite.config.ts
Labels: ✨ Feature

#30 [feature] 글로벌 스타일 세팅 완료
  package-lock.json
  package.json
  src/App.tsx
  src/constants/colors.ts
  src/styles/GlobalStyles.tsx
  tsconfig.app.json
Labels: ✨ Feature

#32 [settings] Firebase 초기 설정
  .gitignore
  package-lock.json
  package.json
  src/firebaseConfig.ts
Labels: ⚙ Settings, 🔥 Firebase

#33 [feature] 헤더 컴포넌트 제작 완료 #27
  package-lock.json
  package.json
  src/App.tsx
  src/components/Header.tsx
  src/components/NavItem.tsx
  src/components/RootLayout.tsx
  src/interfaces/INavItemProps.ts
  src/styles/GlobalStyles.tsx
Labels: ✨ Feature

#36 [settings] API 구조화 작업
  src/api/auth/login.ts
  src/api/auth/logout.ts
  src/api/schedule/createPersonalSchedule.ts
  src/api/schedule/deletePersonalSchedule.ts
  src/api/schedule/getOfficialSchedule.ts
  src/api/schedule/getPersonalSchedule.ts
  src/api/schedule/updatePersonalSchedule.ts
  src/api/user/getUserInfo.ts
  src/api/work/createCorrection.ts
  src/api/work/getCorrection.ts
  src/api/work/getWage.ts
Labels: ⚙ Settings

#37 [feature] 레이아웃 컴포넌트 완성 #28
  src/App.tsx
  src/assets/logo.svg
  src/components/Content.tsx
  src/components/Header.tsx
  src/components/Layout.tsx
  src/components/Menu.tsx
  src/components/NavItem.tsx
  src/components/RootLayout.tsx
  src/pages/Home.tsx
  src/pages/Profile.tsx
  src/pages/Schedule/Schedule.tsx
  src/pages/Schedule/ScheduleDetail.tsx
  src/pages/Wage/Correction/Correction.tsx
  src/pages/Wage/Correction/CorrectionDetail.tsx
  src/pages/Wage/Correction/CorrectionRequest.tsx
  src/pages/Wage/Wage.tsx
  src/pages/Wage/WageCheck/WageCheck.tsx
  src/pages/Wage/WageCheck/WageCheckDetail.tsx
Labels: ✨ Feature

#48 [feat] fontSize 변수 정의 및 레이아웃 변경에 관련된 개선 사항
  src/App.css
  src/App.tsx
  src/assets/react.svg
  src/constants/font.ts
  src/index.css
  src/interfaces/menu.d.ts
  src/layout/Content.tsx
  src/layout/Header.tsx
  src/layout/Layout.tsx
  src/layout/Menu/Menu.tsx
  src/layout/Menu/MenuItem.tsx
  src/main.tsx
Labels: ✨ Feature
